/**
 * Copyright 2026 aphrody-code
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Browser } from "../src/api/browser.ts";

/**
 * Example 09: AI Extraction (Stagehand-style)
 *
 * Demonstrates how to use the `aiExtract` method to let Claude automatically
 * generate CSS selectors and extract data based on natural language instructions.
 *
 * Requires: ANTHROPIC_API_KEY environment variable.
 *
 * Usage:
 *   ANTHROPIC_API_KEY="sk-ant-..." bun run examples/09-ai-extraction.ts
 */

async function main() {
	if (!Bun.env.ANTHROPIC_API_KEY) {
		console.error("❌ ANTHROPIC_API_KEY environment variable is missing.");
		console.error("Please set it to run this example.");
		process.exit(1);
	}

	console.log("🚀 Starting Bxc AI Extractor...");

	// Open a new page in static mode (fastest, no binary required)
	const page = await Browser.newPage({ profile: "static" }) as import("../src/api/browser.ts").Page;

	const targetUrl = "https://google.com/";
	console.log(`\n🌐 Navigating to ${targetUrl}...`);
	await page.goto(targetUrl);

	const instruction = "Extract the top 5 article titles and their corresponding scores or points.";

	console.log(`\n🧠 Sending instruction to Claude: "${instruction}"`);
	const startTime = Bun.nanoseconds();

	try {
		const { data, selectors } = await page.aiExtract(instruction);

		const elapsed = ((Bun.nanoseconds() - startTime) / 1e6).toFixed(0);
		console.log(`\n✅ Extraction completed in ${elapsed}ms!\n`);

		console.log("CSS Selectors generated by AI:");
		console.log(JSON.stringify(selectors, null, 2));

		console.log("\nExtracted Data:");
		console.log(JSON.stringify(data, null, 2));
	} catch (error) {
		console.error("❌ Extraction failed:", error);
	} finally {
		await page.close();
		console.log("\n👋 Browser closed.");
	}
}

main().catch(console.error);
