/**
 * Copyright 2026 aphrody-code
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generate google-ecosystem-map.json + src/google/atlas.ts directly from the
// SQLite cache (5639+ entries already audited). Bypasses the slow live crawl.
import { Database } from "bun:sqlite";
import { join } from "node:path";

const HOME = process.env.HOME ?? "${process.env.HOME || '/home/ubuntu'}";
const CACHE = join(HOME, ".bunlight/cache.sqlite");
const OUT_JSON = join(HOME, "bunlight/google-ecosystem-map.json");
const OUT_TS = join(HOME, "bunlight/src/google/atlas.ts");

const db = new Database(CACHE, { readonly: true });
const rows = db
	.prepare("SELECT key, payload, is_json FROM cache")
	.all() as Array<{
	key: string;
	payload: Uint8Array | string;
	is_json: number;
}>;

console.log(`[atlas] cache rows: ${rows.length}`);

const audits: Array<Record<string, unknown>> = [];
for (const r of rows) {
	if (r.is_json !== 1) continue;
	try {
		const txt =
			typeof r.payload === "string"
				? r.payload
				: new TextDecoder().decode(r.payload);
		const obj = JSON.parse(txt) as Record<string, unknown>;
		if (typeof obj?.url === "string") audits.push(obj);
	} catch {
		/* skip malformed */
	}
}

console.log(`[atlas] parseable audits: ${audits.length}`);

await Bun.write(OUT_JSON, JSON.stringify(audits, null, 2));
console.log(
	`[atlas] wrote ${OUT_JSON} (${Bun.file(OUT_JSON).size.toLocaleString()} B)`,
);

// --- Aggregate stats ---
const cdnStats = new Map<string, number>();
const frameworkStats = new Map<string, number>();
const hostByFramework = new Map<string, Set<string>>();
const hostByCdn = new Map<string, Set<string>>();
const allHosts = new Set<string>();

for (const a of audits) {
	const url = String(a.url);
	let host = "";
	try {
		host = new URL(url).hostname;
	} catch {
		continue;
	}
	allHosts.add(host);

	const cdn = String(a.cdn ?? "GFE");
	cdnStats.set(cdn, (cdnStats.get(cdn) ?? 0) + 1);
	if (!hostByCdn.has(cdn)) hostByCdn.set(cdn, new Set());
	hostByCdn.get(cdn)!.add(host);

	const g = a.google as { framework?: string } | undefined;
	const fw = g?.framework && g.framework !== "none" ? g.framework : "unknown";
	frameworkStats.set(fw, (frameworkStats.get(fw) ?? 0) + 1);
	if (!hostByFramework.has(fw)) hostByFramework.set(fw, new Set());
	hostByFramework.get(fw)!.add(host);
}

console.log(`[atlas] unique hosts: ${allHosts.size}`);

// --- Generate src/google/atlas.ts ---
const sortedCdn = [...cdnStats.entries()].sort((a, b) => b[1] - a[1]);
const sortedFw = [...frameworkStats.entries()].sort((a, b) => b[1] - a[1]);

function recordFromHostSets(m: Map<string, Set<string>>): string {
	const entries = [...m.entries()]
		.sort((a, b) => b[1].size - a[1].size)
		.map(
			([k, set]) =>
				`  ${JSON.stringify(k)}: ${JSON.stringify([...set].sort())},`,
		);
	return `{\n${entries.join("\n")}\n}`;
}

const ts = `// AUTO-GENERATED by scripts/atlas-from-cache.ts — DO NOT EDIT.
// Source: ~/.bunlight/cache.sqlite (${audits.length} audits, ${allHosts.size} unique hosts)
// Generated: ${new Date().toISOString()}

export interface AtlasStats {
  readonly totalAudits: number;
  readonly uniqueHosts: number;
}

export const ATLAS_STATS: AtlasStats = ${JSON.stringify(
	{ totalAudits: audits.length, uniqueHosts: allHosts.size },
	null,
	2,
)};

export const CDN_COUNTS: ReadonlyArray<readonly [string, number]> = ${JSON.stringify(sortedCdn, null, 2)};

export const FRAMEWORK_COUNTS: ReadonlyArray<readonly [string, number]> = ${JSON.stringify(sortedFw, null, 2)};

export const HOSTS_BY_CDN: Readonly<Record<string, ReadonlyArray<string>>> = ${recordFromHostSets(hostByCdn)};

export const HOSTS_BY_FRAMEWORK: Readonly<Record<string, ReadonlyArray<string>>> = ${recordFromHostSets(hostByFramework)};

export const ALL_HOSTS: ReadonlyArray<string> = ${JSON.stringify(
	[...allHosts].sort(),
	null,
	2,
)};

/** Quick lookup: hostname -> framework (best-effort). */
export const FRAMEWORK_BY_HOST: Readonly<Record<string, string>> = (() => {
  const out: Record<string, string> = {};
  for (const [fw, hosts] of Object.entries(HOSTS_BY_FRAMEWORK)) {
    for (const h of hosts) if (!(h in out)) out[h] = fw;
  }
  return out;
})();

/** Quick lookup: hostname -> cdn. */
export const CDN_BY_HOST: Readonly<Record<string, string>> = (() => {
  const out: Record<string, string> = {};
  for (const [cdn, hosts] of Object.entries(HOSTS_BY_CDN)) {
    for (const h of hosts) if (!(h in out)) out[h] = cdn;
  }
  return out;
})();
`;

await Bun.write(OUT_TS, ts);
console.log(
	`[atlas] wrote ${OUT_TS} (${Bun.file(OUT_TS).size.toLocaleString()} B)`,
);

console.log(
	`\nCDN top 5: ${sortedCdn
		.slice(0, 5)
		.map(([k, n]) => `${k}=${n}`)
		.join(", ")}`,
);
console.log(
	`Framework top 5: ${sortedFw
		.slice(0, 5)
		.map(([k, n]) => `${k}=${n}`)
		.join(", ")}`,
);

db.close();
console.log("[atlas] done.");
