#!/usr/bin/env bun
/**
 * scan-bunlight-refs.ts — Bun-native second-pass scanner.
 *
 * Reads reports/scan-v1-bash.json, then re-scans every flagged file to
 * produce a richer inventory:
 *   - per-occurrence line/column/axis/context/proposed-rename
 *   - per-file workspace + category classification + risk
 *   - rename plan across 7 axes (kebab/Pascal/SCREAMING/snake/npm/ffi/path)
 *   - directory + file renames detected from the path tree
 *   - skip list for content the rebrand must NOT touch (frozen benchmark
 *     results, CHANGELOG snapshots, vendor copies, etc.)
 *
 * Output: reports/scan-v2-bun.json
 *
 * Usage:
 *   bun scripts/scan-bunlight-refs.ts                 # default IO
 *   bun scripts/scan-bunlight-refs.ts --to=glw        # alt target name
 *   bun scripts/scan-bunlight-refs.ts --in=path.json --out=path.json
 */

import { resolve } from "node:path";

// -------------------------------------------------------------------------
// Configuration
// -------------------------------------------------------------------------

interface Axis {
	/** Stable id used in the JSON output. */
	id: "npm_scope" | "ffi" | "path" | "SCREAMING" | "Pascal" | "snake" | "kebab";
	/** Regex matching the source token. Order matters in `AXES` (most-specific
	 *  first) — the first axis whose regex matches a position wins. */
	pattern: RegExp;
	/** Function producing the proposed replacement for a captured match. */
	rename: (match: string, to: string) => string;
}

const AXES: ReadonlyArray<Axis> = [
	{
		id: "npm_scope",
		pattern: /@aphrody-code\/bunlight\b/g,
		rename: (_m, to) => `@aphrody-code/${to}`,
	},
	{
		id: "ffi",
		pattern: /\blibbunlight(_rust_bridge)?\b/g,
		rename: (m, to) => m.replace(/bunlight/, to),
	},
	{
		id: "path",
		pattern: /\.bunlight\//g,
		rename: (_m, to) => `.${to}/`,
	},
	{
		id: "SCREAMING",
		pattern: /\bBUNLIGHT_/g,
		rename: (_m, to) => `${to.toUpperCase()}_`,
	},
	{
		id: "Pascal",
		pattern: /\bBunlight\b/g,
		rename: (_m, to) => capitalize(to),
	},
	{
		id: "snake",
		pattern: /\bbunlight_/g,
		rename: (_m, to) => `${to}_`,
	},
	{
		id: "kebab",
		pattern: /\bbunlight\b/g,
		rename: (_m, to) => to,
	},
];

/** Directories the rebrand must skip entirely. */
const SKIP_DIRS: ReadonlyArray<string> = [
	".git",
	"node_modules",
	"vendor",
	"dist",
	"rust-bridge/target",
	".turbo",
	".bunlight",
];

/** Per-file skip rules — files matched here are reported but tagged
 *  risk=keep (the rebrand should leave them untouched). */
const SKIP_FILES: ReadonlyArray<RegExp> = [
	/^benchmarks\/results\/\d{4}-\d{2}-\d{2}/, // historical benchmark snapshots
	/^CHANGELOG\.md$/, // history — append only
	/^bun\.lock$/, // regenerated by `bun install`
	/^bunlight-memory\.sqlite$/, // runtime artifact
	/^\.tsbuildinfo$/,
];

/** Files that need MANUAL review because the change is non-textual or
 *  affects identifiers across multiple boundaries. */
const MANUAL_REVIEW_PATTERNS: ReadonlyArray<RegExp> = [
	/^rust-bridge\/.*\.(rs|toml)$/, // Rust crate name, symbol exports
	/^.*\.ps1$/, // PowerShell installer paths
	/^install\.sh$/, // POSIX installer paths
	/package\.json$/, // npm scope changes ripple to lockfile
];

/** Workspace classification — used to route the rename plan execution. */
const WORKSPACE_RULES: Array<{ id: string; match: RegExp }> = [
	{ id: "rust-bridge", match: /^rust-bridge\// },
	{ id: "scripts", match: /^scripts\// },
	{ id: "benchmarks", match: /^benchmarks\// },
	{ id: "test", match: /^test\// },
	{ id: "docs", match: /^docs\// },
	{ id: "examples", match: /^examples\// },
	{ id: "packages/api", match: /^packages\/api\// },
	{ id: "packages/llm-extract", match: /^packages\/llm-extract\// },
	{
		id: "packages/bunlight-extension",
		match: /^packages\/bunlight-extension\//,
	},
	{ id: "packages/other", match: /^packages\// },
	{ id: "src", match: /^src\// },
	{ id: "github-workflows", match: /^\.github\// },
	{ id: "claude-config", match: /^\.claude\// },
	{ id: "root", match: /^[^/]+$/ },
];

const FILE_CATEGORY: Array<{ id: string; match: RegExp }> = [
	{ id: "lockfile", match: /(bun\.lock|package-lock\.json|Cargo\.lock)$/ },
	{ id: "build-info", match: /\.tsbuildinfo$/ },
	{ id: "config", match: /\.(json|toml|yml|yaml|jsonc|ini)$/ },
	{ id: "markdown", match: /\.md$/ },
	{ id: "rust", match: /\.rs$/ },
	{ id: "powershell", match: /\.ps1$/ },
	{ id: "shell", match: /\.(sh|bash)$/ },
	{ id: "typescript", match: /\.(ts|tsx)$/ },
	{ id: "javascript", match: /\.(js|jsx|mjs|cjs)$/ },
	{ id: "html", match: /\.(html|htm)$/ },
	{ id: "css", match: /\.(css|scss|less)$/ },
];

// -------------------------------------------------------------------------
// Types
// -------------------------------------------------------------------------

interface ScanV1 {
	scan_metadata: {
		repo_root: string;
		git_head: string;
		git_dirty: boolean;
		timestamp: string;
	};
	summary: {
		total_files_with_matches: number;
		total_occurrences: number;
	};
	files: Array<{
		path: string;
		matches: number;
		patterns: string[];
	}>;
}

interface Occurrence {
	line: number;
	column: number;
	axis: Axis["id"];
	match: string;
	context: string;
	proposed_rename: string;
}

interface FileEntry {
	path: string;
	workspace: string;
	category: string;
	total_matches: number;
	by_axis: Record<string, number>;
	risk: "safe" | "manual_review" | "keep";
	occurrences: Occurrence[];
}

interface RenameTarget {
	from: string;
	to: string;
	kind: "file" | "directory";
	reason: string;
}

// -------------------------------------------------------------------------
// Helpers
// -------------------------------------------------------------------------

function capitalize(s: string): string {
	return s.length === 0 ? s : s[0]!.toUpperCase() + s.slice(1);
}

function classify<T extends { id: string; match: RegExp }>(
	rules: ReadonlyArray<T>,
	path: string,
): string {
	for (const r of rules) {
		if (r.match.test(path)) return r.id;
	}
	return "unclassified";
}

function fileRisk(relPath: string): FileEntry["risk"] {
	for (const rx of SKIP_FILES) if (rx.test(relPath)) return "keep";
	for (const rx of MANUAL_REVIEW_PATTERNS) {
		if (rx.test(relPath)) return "manual_review";
	}
	return "safe";
}

function parseArgs(argv: string[]) {
	const out = {
		inPath: "reports/scan-v1-bash.json",
		outPath: "reports/scan-v2-bun.json",
		to: "bxc",
	};
	for (const arg of argv) {
		const eq = arg.indexOf("=");
		if (eq === -1) continue;
		const key = arg.slice(0, eq).replace(/^--/, "");
		const val = arg.slice(eq + 1);
		if (key === "in") out.inPath = val;
		else if (key === "out") out.outPath = val;
		else if (key === "to") out.to = val;
	}
	return out;
}

function findOccurrences(
	content: string,
	to: string,
): { axis: Record<string, number>; occurrences: Occurrence[] } {
	const occurrences: Occurrence[] = [];
	const axisCounts: Record<string, number> = {};
	const claimed = new Set<number>();

	// line index — running pre-computed offset → line/column.
	const lineStarts: number[] = [0];
	for (let i = 0; i < content.length; i++) {
		if (content.charCodeAt(i) === 10) lineStarts.push(i + 1);
	}
	function locate(offset: number): { line: number; column: number } {
		// binary search
		let lo = 0;
		let hi = lineStarts.length - 1;
		while (lo <= hi) {
			const mid = (lo + hi) >>> 1;
			const start = lineStarts[mid]!;
			if (start > offset) hi = mid - 1;
			else lo = mid + 1;
		}
		const line = hi + 1;
		const lineStart = lineStarts[hi]!;
		return { line, column: offset - lineStart + 1 };
	}

	for (const axis of AXES) {
		axis.pattern.lastIndex = 0;
		let m: RegExpExecArray | null;
		while ((m = axis.pattern.exec(content)) !== null) {
			const offset = m.index;
			// Skip if a more-specific axis already claimed this byte.
			if (claimed.has(offset)) continue;
			for (let k = 0; k < m[0].length; k++) claimed.add(offset + k);

			const { line, column } = locate(offset);
			const lineStart = lineStarts[line - 1]!;
			const lineEnd =
				line < lineStarts.length ? lineStarts[line]! - 1 : content.length;
			const contextLine = content
				.slice(lineStart, lineEnd)
				.replace(/\t/g, "  ");
			// Cap context to 220 chars centered on the match.
			const ctxRel = column - 1;
			const head = Math.max(0, ctxRel - 80);
			const tail = Math.min(contextLine.length, ctxRel + m[0].length + 80);
			const context =
				(head > 0 ? "…" : "") +
				contextLine.slice(head, tail) +
				(tail < contextLine.length ? "…" : "");

			occurrences.push({
				line,
				column,
				axis: axis.id,
				match: m[0],
				context,
				proposed_rename: axis.rename(m[0], to),
			});
			axisCounts[axis.id] = (axisCounts[axis.id] ?? 0) + 1;
		}
	}

	// Stable sort by file location.
	occurrences.sort((a, b) =>
		a.line === b.line ? a.column - b.column : a.line - b.line,
	);
	return { axis: axisCounts, occurrences };
}

async function discoverRenameTargets(
	repoRoot: string,
	to: string,
): Promise<RenameTarget[]> {
	const out: RenameTarget[] = [];
	const glob = new Bun.Glob("**/*");
	for await (const entry of glob.scan({
		cwd: repoRoot,
		onlyFiles: false,
		dot: true,
	})) {
		// skip excluded dirs
		if (SKIP_DIRS.some((d) => entry === d || entry.startsWith(`${d}/`))) {
			continue;
		}
		const base = entry.split("/").pop()!;
		// We match the lowercase form because "Bunlight" never appears in paths.
		if (!/bunlight/.test(base)) continue;
		const renamed = base.replace(/bunlight/g, to);
		const newPath = entry
			.replace(/\/?[^/]+$/, `/${renamed}`)
			.replace(/^\//, "");
		// is directory?
		const stat = await Bun.file(resolve(repoRoot, entry))
			.stat()
			.catch(() => null);
		const kind: "file" | "directory" =
			stat && (stat as { isDirectory?: () => boolean }).isDirectory?.()
				? "directory"
				: "file";
		out.push({
			from: entry,
			to: newPath,
			kind,
			reason: `path token "${base}" → "${renamed}"`,
		});
	}
	return out;
}

// -------------------------------------------------------------------------
// Main
// -------------------------------------------------------------------------

async function main() {
	const args = parseArgs(process.argv.slice(2));
	const to = args.to;

	const v1Raw = await Bun.file(args.inPath).text();
	const v1 = JSON.parse(v1Raw) as ScanV1;
	const repoRoot = v1.scan_metadata.repo_root;

	const files: FileEntry[] = [];
	let totalOcc = 0;
	const axisTotals: Record<string, number> = {};

	// Process every file in the v1 list — these are guaranteed to contain
	// at least one match (rg --files-with-matches semantic).
	await Promise.all(
		v1.files.map(async (entry) => {
			const abs = resolve(repoRoot, entry.path);
			let content: string;
			try {
				content = await Bun.file(abs).text();
			} catch {
				return;
			}
			const { axis, occurrences } = findOccurrences(content, to);
			const risk = fileRisk(entry.path);
			const workspace = classify(WORKSPACE_RULES, entry.path);
			const category = classify(FILE_CATEGORY, entry.path);

			const total = occurrences.length;
			totalOcc += total;
			for (const [k, v] of Object.entries(axis)) {
				axisTotals[k] = (axisTotals[k] ?? 0) + v;
			}

			files.push({
				path: entry.path,
				workspace,
				category,
				total_matches: total,
				by_axis: axis,
				risk,
				occurrences,
			});
		}),
	);

	files.sort((a, b) => b.total_matches - a.total_matches);

	// Rename plan
	const renamePlan = {
		from: "bunlight",
		to,
		axes: {
			npm_scope: {
				"@aphrody-code/bunlight": `@aphrody-code/${to}`,
			},
			ffi: {
				libbunlight: `lib${to}`,
				libbunlight_rust_bridge: `lib${to}_rust_bridge`,
			},
			path: { ".bunlight/": `.${to}/` },
			SCREAMING: { BUNLIGHT_: `${to.toUpperCase()}_` },
			Pascal: { Bunlight: capitalize(to) },
			snake: { bunlight_: `${to}_` },
			kebab: { bunlight: to },
		},
	};

	// Per-workspace and per-risk roll-ups
	const byWorkspace: Record<
		string,
		{ file_count: number; total_matches: number }
	> = {};
	const byRisk: Record<
		FileEntry["risk"],
		{ file_count: number; total_matches: number }
	> = {
		safe: { file_count: 0, total_matches: 0 },
		manual_review: { file_count: 0, total_matches: 0 },
		keep: { file_count: 0, total_matches: 0 },
	};
	for (const f of files) {
		byWorkspace[f.workspace] ??= { file_count: 0, total_matches: 0 };
		byWorkspace[f.workspace]!.file_count += 1;
		byWorkspace[f.workspace]!.total_matches += f.total_matches;
		byRisk[f.risk].file_count += 1;
		byRisk[f.risk].total_matches += f.total_matches;
	}

	const renames = await discoverRenameTargets(repoRoot, to);

	const json = {
		scan_metadata: {
			tool: "bun",
			version: "2.0",
			based_on: args.inPath,
			timestamp: new Date().toISOString(),
			repo_root: repoRoot,
			git_head: v1.scan_metadata.git_head,
			git_dirty: v1.scan_metadata.git_dirty,
			target_name: to,
		},
		summary: {
			total_files: files.length,
			total_occurrences: totalOcc,
			by_axis: axisTotals,
			by_workspace: byWorkspace,
			by_risk: byRisk,
			files_to_rename_count: renames.length,
		},
		rename_plan: renamePlan,
		rename_targets: renames,
		top_files: files.slice(0, 25).map((f) => ({
			path: f.path,
			workspace: f.workspace,
			category: f.category,
			risk: f.risk,
			total_matches: f.total_matches,
			by_axis: f.by_axis,
		})),
		files,
	};

	await Bun.write(args.outPath, `${JSON.stringify(json, null, 2)}\n`);
	console.error(`wrote ${args.outPath}`);
	console.error(
		`  files=${files.length}  occurrences=${totalOcc}  renames=${renames.length}`,
	);
	console.error(`  axes=${JSON.stringify(axisTotals)}`);
	console.error(
		`  by_risk=safe:${byRisk.safe.file_count}/${byRisk.safe.total_matches} ` +
			`manual:${byRisk.manual_review.file_count}/${byRisk.manual_review.total_matches} ` +
			`keep:${byRisk.keep.file_count}/${byRisk.keep.total_matches}`,
	);
}

main().catch((err) => {
	console.error("scan-bunlight-refs.ts failed:", err);
	process.exit(1);
});
