/**
 * Copyright 2026 aphrody-code
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { describe, test, expect, beforeAll, afterAll } from "bun:test";
import { join } from "node:path";
import {
	existsSync,
	rmSync,
	mkdirSync,
	readFileSync,
	writeFileSync,
} from "node:fs";
import { main as actorCliMain } from "../../src/cli/actor.ts";

const TEST_DIR = join(import.meta.dir, "../../dist/test-cli-actor");

describe("Actor CLI Command", () => {
	beforeAll(() => {
		if (existsSync(TEST_DIR)) {
			rmSync(TEST_DIR, { recursive: true, force: true });
		}
		mkdirSync(TEST_DIR, { recursive: true });
		process.env.NODE_ENV = "test";
	});

	afterAll(() => {
		if (existsSync(TEST_DIR)) {
			rmSync(TEST_DIR, { recursive: true, force: true });
		}
	});

	test("actor init creates project structure", async () => {
		const targetProjectDir = join(TEST_DIR, "my-crawler-cli");
		await actorCliMain(
			["init", targetProjectDir],
			{ insecure: false, quiet: true, json: false, timeoutMs: 30000 },
			{ exitProcess: false },
		);

		expect(existsSync(targetProjectDir)).toBe(true);
		expect(existsSync(join(targetProjectDir, "package.json"))).toBe(true);
		expect(existsSync(join(targetProjectDir, "tsconfig.json"))).toBe(true);
		expect(existsSync(join(targetProjectDir, "src", "main.ts"))).toBe(true);

		const packageJson = JSON.parse(
			readFileSync(join(targetProjectDir, "package.json"), "utf8"),
		);
		expect(packageJson.name).toContain("my-crawler-cli");
		expect(packageJson.scripts.start).toBe("bun run src/main.ts");
	});

	test("actor run executes script in a subprocess with input and custom storage", async () => {
		const mockScriptPath = join(TEST_DIR, "mock-actor.ts");
		const runStorageDir = join(TEST_DIR, "run-storage");

		// Write a mock script that imports the Actor SDK
		const mockScriptContent = `
import { Actor } from "${join(import.meta.dir, "../../src/sdk/Actor.ts")}";
await Actor.main(async () => {
	const input = await Actor.getInput() || {};
	await Actor.setValue("OUTPUT", { received: input.val, ok: true });
});
`;
		writeFileSync(mockScriptPath, mockScriptContent, "utf8");

		// Run bxc actor run command
		await actorCliMain(
			[
				"run",
				mockScriptPath,
				"--input",
				JSON.stringify({ val: 777 }),
				"--storage-dir",
				runStorageDir,
			],
			{ insecure: false, quiet: true, json: false, timeoutMs: 30000 },
			{ exitProcess: false },
		);

		// Assert that the input file was populated correctly
		const inputJsonPath = join(
			runStorageDir,
			"key_value_stores",
			"default",
			"INPUT.json",
		);
		expect(existsSync(inputJsonPath)).toBe(true);
		const inputData = JSON.parse(readFileSync(inputJsonPath, "utf8"));
		expect(inputData.val).toBe(777);

		// Assert that the output file was generated by the actor run subprocess
		const outputJsonPath = join(
			runStorageDir,
			"key_value_stores",
			"default",
			"OUTPUT.json",
		);
		expect(existsSync(outputJsonPath)).toBe(true);
		const outputData = JSON.parse(readFileSync(outputJsonPath, "utf8"));
		expect(outputData.received).toBe(777);
		expect(outputData.ok).toBe(true);
	});

	test("actor run executes actor directory with actor.json configuration", async () => {
		const targetProjectDir = join(TEST_DIR, "directory-actor-test");
		mkdirSync(targetProjectDir, { recursive: true });
		mkdirSync(join(targetProjectDir, "src"), { recursive: true });
		
		const actorJson = {
			actorSpecification: 1,
			name: "directory-actor-test",
			run: `bun run ${join(targetProjectDir, "src", "main.ts")}`
		};
		writeFileSync(join(targetProjectDir, "actor.json"), JSON.stringify(actorJson, null, 2), "utf8");

		const mockScriptContent = `
import { Actor } from "${join(import.meta.dir, "../../src/sdk/Actor.ts")}";
await Actor.main(async () => {
	await Actor.setValue("OUTPUT", { success: true });
});
`;
		writeFileSync(join(targetProjectDir, "src", "main.ts"), mockScriptContent, "utf8");

		const runStorageDir = join(TEST_DIR, "directory-storage");

		await actorCliMain(
			[
				"run",
				targetProjectDir,
				"--storage-dir",
				runStorageDir,
			],
			{ insecure: false, quiet: true, json: false, timeoutMs: 30000 },
			{ exitProcess: false },
		);

		const outputJsonPath = join(
			runStorageDir,
			"key_value_stores",
			"default",
			"OUTPUT.json",
		);
		expect(existsSync(outputJsonPath)).toBe(true);
		const outputData = JSON.parse(readFileSync(outputJsonPath, "utf8"));
		expect(outputData.success).toBe(true);
	});
});
